#!/usr/bin/env node

var type = process.argv[2];
var name = process.argv[3];

if(!(type && name)) {
  console.log('You need to provice a [type] and a [name]');
  process.exit(1);
}

var mkdirp = require('mkdirp');
var fs     = require('fs');
var _      = require('lodash');

var path     = './client/routes/' + name;
var segments = name.split('/').filter(Boolean);

var destinationFile = path + '/' + _.last(segments);
var templateName    = segments.map(_.capitalize).join('');

// create path
mkdirp.sync(path);

// create html file
generateFile('html', templateName);

// create js file
generateFile('js', templateName);

console.log('SUCCESS');

function generateFile(fileExt, templateName){
  var blueprint = __dirname + '/blueprints/route/blueprint';
  var content = fs.readFileSync(blueprint + '.' + fileExt, 'utf8');
  content = content.replace(/\_\_NAME\_\_/g, templateName);
  fs.writeFileSync(destinationFile + '.' + fileExt, content);
};
